# Validate exact compiler targets, including architecture/family feature suffixes.
if(NOT DEFINED ASTRAI_CUDA_ARCH AND DEFINED ENV{ASTRAI_CUDA_ARCH})
    set(ASTRAI_CUDA_ARCH "$ENV{ASTRAI_CUDA_ARCH}")
endif()
set(ASTRAI_CUDA_ARCH_LIST "")
if(ASTRAI_CUDA_ARCH)
    string(REPLACE ";" " " _arch_tokens "${ASTRAI_CUDA_ARCH}")
    separate_arguments(ASTRAI_CUDA_ARCH_LIST NATIVE_COMMAND "${_arch_tokens}")
    list(REMOVE_DUPLICATES ASTRAI_CUDA_ARCH_LIST)
endif()

function(astrai_arch_number token out)
    if(NOT token MATCHES "^([0-9]+)(a|f)?$")
        message(FATAL_ERROR "Invalid CUDA target '${token}': expected CC digits with optional a/f")
    endif()
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

set(_probe_dir "${CMAKE_CURRENT_BINARY_DIR}/arch_probe/${CMAKE_CUDA_COMPILER_VERSION}")
file(MAKE_DIRECTORY "${_probe_dir}")
file(WRITE "${_probe_dir}/probe.cu" "__global__ void probe() {}\n")
foreach(token IN LISTS ASTRAI_CUDA_ARCH_LIST)
    astrai_arch_number("${token}" cc)
    if(cc LESS 80)
        message(FATAL_ERROR "AstrAI CUDA kernels require SM80 or newer: ${token}")
    endif()
    if(NOT EXISTS "${_probe_dir}/${token}.o")
        execute_process(
            COMMAND "${CMAKE_CUDA_COMPILER}" -c "${_probe_dir}/probe.cu"
                "--generate-code=arch=compute_${token},code=sm_${token}"
                -o "${_probe_dir}/${token}.o"
            RESULT_VARIABLE status ERROR_VARIABLE error)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "CUDA ${CMAKE_CUDA_COMPILER_VERSION} cannot build ${token}:\n${error}")
        endif()
    endif()
endforeach()

# Explicit gencode avoids implicit baseline images for feature-specific targets.
set(CMAKE_CUDA_ARCHITECTURES OFF CACHE STRING "Managed by ASTRAI_CUDA_ARCH" FORCE)
function(astrai_target_arches target)
    set_target_properties(${target} PROPERTIES CUDA_ARCHITECTURES OFF)
    foreach(token IN LISTS ARGN)
        target_compile_options(${target} PRIVATE
            "$<$<COMPILE_LANGUAGE:CUDA>:--generate-code=arch=compute_${token},code=[sm_${token},compute_${token}]>")
    endforeach()
endfunction()

set(ASTRAI_FP8_ARCHES "")
set(ASTRAI_TMA_ARCHES "")
set(ASTRAI_MX_ARCHES "")
foreach(token IN LISTS ASTRAI_CUDA_ARCH_LIST)
    astrai_arch_number("${token}" cc)
    if(cc GREATER_EQUAL 89)
        list(APPEND ASTRAI_FP8_ARCHES "${token}")
    endif()
    if(cc GREATER_EQUAL 90)
        list(APPEND ASTRAI_TMA_ARCHES "${token}")
    endif()
    if(token MATCHES "^120(a|f)$")
        list(APPEND ASTRAI_MX_ARCHES "${token}")
    endif()
endforeach()

file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(_manifest "${CMAKE_CURRENT_BINARY_DIR}/generated/gemm_build.h")
file(WRITE "${_manifest}" "#pragma once\n#include <utils/arch.h>\n")
foreach(feature FP8 TMA MX)
    if(ASTRAI_${feature}_ARCHES)
        file(APPEND "${_manifest}" "#define ASTRAI_BUILD_${feature} 1\n")
    else()
        file(APPEND "${_manifest}" "#define ASTRAI_BUILD_${feature} 0\n")
    endif()
endforeach()
file(APPEND "${_manifest}" "namespace astrai::gemm::build {\n")
function(astrai_manifest_targets name)
    set(rows "")
    foreach(token IN LISTS ARGN)
        string(REGEX MATCH "^([0-9]+)(a|f)?$" match "${token}")
        set(cc "${CMAKE_MATCH_1}")
        set(feature "${CMAKE_MATCH_2}")
        if(feature)
            string(APPEND rows "{${cc}, '${feature}'},")
        else()
            string(APPEND rows "{${cc}, 0},")
        endif()
    endforeach()
    if(NOT rows)
        set(rows "{0, 0}")
    endif()
    file(APPEND "${_manifest}" "inline constexpr CudaTarget k${name}[] = {${rows}};\n")
endfunction()
astrai_manifest_targets(Base ${ASTRAI_CUDA_ARCH_LIST})
astrai_manifest_targets(Fp8 ${ASTRAI_FP8_ARCHES})
astrai_manifest_targets(Tma ${ASTRAI_TMA_ARCHES})
astrai_manifest_targets(Mx ${ASTRAI_MX_ARCHES})
file(APPEND "${_manifest}"
    "inline constexpr const char* kTargets = \"${ASTRAI_CUDA_ARCH_LIST}\";\n}\n")
